### ISSUE TITLE
PG3 Shelly suspect false notices

### ISSUE THREAD

**Issue by mrwkbrdr** [UniversalDevicesInc-PG3/udi-shelly-poly#1]
Node server unwanted notices messages.
The node server allows me to clear the notices but they re-appear immediately. 

The notice "waiting for valid user config" should dissappear after a valid config has been established? 

See screen shots attached and log files.
![Shelly notices](https://user-images.githubusercontent.com/96545553/199069253-48eff678-7ac4-467c-9795-5a67a56470f6.jpg)
![Shelly notices](https://user-images.githubusercontent.com/96545553/199069387-9ca7adb9-31f9-4b23-83bf-d64d8bb07d1f.jpg)

Thank you 
[ShellyRGBW2_10-31-2022_112017-AM.zip](https://github.com/UniversalDevicesInc-PG3/udi-shelly-poly/files/9903390/ShellyRGBW2_10-31-2022_112017-AM.zip)

**Comment by bpaauwe** [comment]
They reappear because the condition causing still exists.  It doesn't like the IP address you entered, it doesn't think it is valid.  What IP addresses are you using?

I didn't write this and don't really maintain it, I simply ported it from PG2 to PG3.

**Comment by mrwkbrdr** [comment]
The IP address is 10.0.0.16

Gotcha on the node server writer. I'm guessing not many are using this node server, as the developer is no longer.

Thanks,

**Comment by bpaauwe** [comment]
Try version 2.0.4. I change the minimum length of the IP address so it should accept yours now.

First, click the refresh store button and go to the shelly node server and verify that you see version 2.0.4 in the details page.
Second, restart the node server, it should auto update to version 2.0.4

**Comment by mrwkbrdr** [comment]
2.04 corrected both unwanted notices.

Thank you,

Please close this issue as resolved with update 2.04
